### ISSUE TITLE
[Documentation] ABSTRACT should replace "contagious unknown" to "monadic zero"

### ISSUE THREAD

**Issue by robrwo** [perlancar/perl-List-AllUtils-Null#1]
The technical term used by modern computer scientists is "monadic zero".  So the abstract should be something like "list functions that treat undef like a monadic zero".

**Comment by perlancar** [comment]
Thanks for the suggestion. Though technically more accurate, I think it's too technical :)

**Comment by robrwo** [comment]
Worth at least using the term in the description, so that it shows up in keyword searches.

**Comment by perlancar** [comment]
Done, thanks.
